#pragma once
#ifdef  _DEBUG
	#define DEBUG_LEXER_TRACE
	#define DEBUG_PARSER_TRACE
	#define DEBUG_COMPILER_TRACE
	#define DEBUG_INTERPRETER_STACK_TRACE
	#define DEBUG_INTERPRETER_INSTRUCTION_TRACE
#endif