#pragma once
#define DEBUG_VM_STACK_TRACE
#define DEBUG_COMPILER_TRACE
#define DEBUG_VM_INSTRUCTION_TRACE

#undef DEBUG_VM_STACK_TRACE
//#undef DEBUG_VM_INSTRUCTION_TRACE
//#undef DEBUG_COMPILER_TRACE